version: "3.9"

services:
  endee-db:
    image: enterprise-knowledge-copilot-endee-db:latest
    container_name: endee-db
    ports:
      - "8080:8080"
    networks:
      - copilot-net
      
  endee-service:
    image: enterprise-knowledge-copilot-endee-service:latest
    container_name: endee-service
    ports:
      - "8000:8000"
    depends_on:
      - endee-db
    environment:
      - ENDEE_DB_URL=http://endee-db:8080
    networks:
      - copilot-net

  langchain-service:
    image: enterprise-knowledge-copilot-langchain-service:latest
    container_name: langchain-service
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - endee-service
    environment:
      - ENDEE_SERVICE_URL=http://endee-service:8000
    networks:
      - copilot-net

networks:
  copilot-net:
    driver: bridge
