services:
  endee-db:
    image: enterprise-knowledge-copilot-endee-db:latest
    build:
      context: ./endee-db
      dockerfile: infra/Dockerfile
      args:
        BUILD_ARCH: avx2
    ports:
      - "8080:8080"
    networks:
      - copilot-net

  endee-service:
    image: enterprise-knowledge-copilot-endee-service:latest
    build:
      context: ./endee-service
    ports:
      - "8000:8000"
    depends_on:
      - endee-db
    environment:
      - ENDEE_DB_URL=http://endee-db:8080
    networks:
      - copilot-net

  langchain-service:
    image: enterprise-knowledge-copilot-langchain-service:latest
    build:
      context: ./langchain-service
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - endee-service
    environment:
      - ENDEE_SERVICE_URL=http://endee-service:8000
      - STREAMLIT_SERVER_BASE_URL_PATH=/enterprise-copilot
    networks:
      - copilot-net

networks:
  copilot-net:
    driver: bridge
